# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AirportJson < Formula
  desc "JSONize airport -I of macOS"
  homepage ""
  version "0.0.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pen/airport-json/releases/download/v0.0.1/airport-json_0.0.1_darwin_arm64.zip"
      sha256 "708ee3ad912fb40a6a8a9a3cf98d9b19d299035d8044df92181a50fa3198c16c"

      def install
        bin.install "airport-json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pen/airport-json/releases/download/v0.0.1/airport-json_0.0.1_darwin_amd64.zip"
      sha256 "eb3dc4f443b183655ea757228a45ab313db04df55c9f05ac850c1589db347d3f"

      def install
        bin.install "airport-json"
      end
    end
  end
end
